import type { AgentTemplate, AgentTemplateKey } from "@rtos/shared-types";

export const AGENT_TEMPLATES: Record<AgentTemplateKey, AgentTemplate> = {
  "cve-monitor": {
    role: "CVE Monitoring Agent",
    capabilities: ["cve-tracking", "vulnerability-intelligence", "threat-correlation"],
    skills: ["NVD API", "CISA KEV", "CVE Analysis", "CVSS Scoring"],
    permissions: [{ type: "network", scope: "*", granted: true }],
    isBackgroundAgent: true,
  },
  "jr-ceo": {
    role: "Junior CEO",
    capabilities: ["agent-management", "task-delegation", "resource-allocation"],
    skills: ["Leadership", "Coordination", "Budget Management"],
    permissions: [],
  },
  "crypto-trader": {
    role: "Crypto Trading Agent",
    capabilities: ["dex-trading", "cex-trading", "arbitrage", "portfolio-management"],
    skills: ["Technical Analysis", "DeFi", "Smart Contracts", "MEV"],
    permissions: [],
  },
  "stock-trader": {
    role: "Stock Trading Agent",
    capabilities: ["equity-trading", "options-trading", "market-analysis"],
    skills: ["Fundamental Analysis", "Options", "Quant Analysis"],
    permissions: [],
  },
  "defi-manager": {
    role: "DeFi Portfolio Manager",
    capabilities: ["yield-farming", "liquidity-provision", "staking"],
    skills: ["Smart Contracts", "Gas Optimization", "Protocol Analysis"],
    permissions: [],
  },
  "nft-agent": {
    role: "NFT Trading Agent",
    capabilities: ["nft-analysis", "marketplace-trading", "rarity-tracking"],
    skills: ["NFT Valuation", "Marketplace APIs", "Trend Detection"],
    permissions: [],
  },
  "mev-bot": {
    role: "MEV Bot Agent",
    capabilities: ["sandwich-attacks", "arbitrage", "liquidations"],
    skills: ["Flashbots", "Mempool Monitoring", "Bundle Creation"],
    permissions: [],
  },
  "market-maker": {
    role: "Market Making Agent",
    capabilities: ["liquidity-provision", "spread-management"],
    skills: ["Order Book Dynamics", "HFT", "Risk Management"],
    permissions: [],
  },
  "smart-contract-auditor": {
    role: "Smart Contract Auditor",
    capabilities: ["vulnerability-scanning", "code-review", "exploit-detection"],
    skills: ["Solidity", "Vyper", "Slither", "Mythril", "Foundry"],
    permissions: [],
  },
  "poc-exploit-dev": {
    role: "PoC Exploit Developer",
    capabilities: ["exploit-creation", "vulnerability-reproduction"],
    skills: ["Exploit Development", "Foundry", "Smart Contract Hacking"],
    permissions: [],
  },
  "contract-fuzzer": {
    role: "Smart Contract Fuzzer",
    capabilities: ["fuzzing", "invariant-testing", "property-testing"],
    skills: ["Echidna", "Foundry Fuzz", "Medusa", "Formal Verification"],
    permissions: [],
  },
  "reentrancy-hunter": {
    role: "Reentrancy Vulnerability Hunter",
    capabilities: ["reentrancy-detection", "cross-function-analysis"],
    skills: ["Reentrancy Patterns", "CEI Pattern Analysis"],
    permissions: [],
  },
  "defi-protocol-analyzer": {
    role: "DeFi Protocol Analyzer",
    capabilities: ["protocol-analysis", "economic-exploit-detection"],
    skills: ["DeFi Mechanics", "Flash Loan Attacks", "Oracle Design"],
    permissions: [],
  },
  "pentester": {
    role: "Penetration Tester",
    capabilities: ["vulnerability-assessment", "exploit-testing", "red-team-ops"],
    skills: ["Metasploit", "Burp Suite", "Nmap", "Custom Exploits"],
    permissions: [],
  },
  "web3-pentester": {
    role: "Web3 Penetration Tester",
    capabilities: ["wallet-security", "dapp-testing", "bridge-security"],
    skills: ["Metamask Phishing", "Web3.js", "Ethers.js"],
    permissions: [],
  },
  "zero-day-hunter": {
    role: "Zero-Day Vulnerability Hunter",
    capabilities: ["0day-discovery", "reverse-engineering"],
    skills: ["IDA Pro", "Ghidra", "Binary Exploitation", "Fuzzing"],
    permissions: [],
  },
  "ransomware-analyst": {
    role: "Ransomware Analysis Agent",
    capabilities: ["malware-analysis", "decryption-research"],
    skills: ["Malware RE", "Cryptography", "Network Analysis"],
    permissions: [],
  },
  "api-fuzzer": {
    role: "API Fuzzing Agent",
    capabilities: ["api-fuzzing", "endpoint-discovery", "auth-bypass"],
    skills: ["Burp Suite", "FFUF", "REST/GraphQL", "JWT Analysis"],
    permissions: [],
  },
  "defense-analyst": {
    role: "Defense Analyst",
    capabilities: ["threat-detection", "incident-response", "forensics"],
    skills: ["SIEM", "IDS/IPS", "Threat Intel", "EDR"],
    permissions: [],
  },
  "soc-analyst": {
    role: "SOC Analyst Agent",
    capabilities: ["alert-triage", "threat-hunting"],
    skills: ["Splunk", "ELK Stack", "Suricata", "MITRE ATT&CK"],
    permissions: [],
  },
  "threat-intel": {
    role: "Threat Intelligence Agent",
    capabilities: ["ioc-collection", "apt-tracking", "dark-web-monitoring"],
    skills: ["OSINT", "TOR", "Threat Feeds", "APT Reports"],
    permissions: [],
  },
  "honeypot-manager": {
    role: "Honeypot Manager",
    capabilities: ["honeypot-deployment", "attacker-tracking"],
    skills: ["Cowrie", "Dionaea", "T-Pot", "Deception Technology"],
    permissions: [],
  },
  "blockchain-analyst": {
    role: "Blockchain Analytics Agent",
    capabilities: ["on-chain-analysis", "wallet-tracking"],
    skills: ["Etherscan", "Dune Analytics", "Chainalysis"],
    permissions: [],
  },
  "wallet-tracker": {
    role: "Wallet Tracking Agent",
    capabilities: ["whale-watching", "wallet-profiling"],
    skills: ["Address Clustering", "Behavior Analysis"],
    permissions: [],
  },
  "rugpull-detector": {
    role: "Rug Pull Detection Agent",
    capabilities: ["scam-detection", "token-analysis"],
    skills: ["Token Sniffer", "Liquidity Analysis"],
    permissions: [],
  },
  "bridge-monitor": {
    role: "Cross-Chain Bridge Monitor",
    capabilities: ["bridge-monitoring", "exploit-detection"],
    skills: ["Bridge Protocols", "Multi-chain Analysis"],
    permissions: [],
  },
  "web-scraper": {
    role: "Web Scraper Agent",
    capabilities: ["data-extraction", "web-crawling"],
    skills: ["Selenium", "Scrapy", "Proxy Management"],
    permissions: [],
  },
  "osint-investigator": {
    role: "OSINT Investigation Agent",
    capabilities: ["person-tracking", "social-media-analysis"],
    skills: ["Maltego", "Shodan", "Recon-ng", "TheHarvester"],
    permissions: [],
  },
  "dark-web-monitor": {
    role: "Dark Web Monitoring Agent",
    capabilities: ["dark-web-scraping", "leak-detection"],
    skills: ["TOR", "I2P", "Dark Web Markets"],
    permissions: [],
  },
  "credential-hunter": {
    role: "Credential Leak Hunter",
    capabilities: ["breach-monitoring", "credential-stuffing"],
    skills: ["HaveIBeenPwned", "Dehashed", "Password Lists"],
    permissions: [],
  },
  "ml-model-builder": {
    role: "ML Model Builder",
    capabilities: ["model-training", "feature-engineering"],
    skills: ["PyTorch", "TensorFlow", "Scikit-learn", "XGBoost"],
    permissions: [],
  },
  "llm-security-tester": {
    role: "LLM Security Tester",
    capabilities: ["prompt-injection", "jailbreak-testing"],
    skills: ["Prompt Engineering", "Adversarial ML"],
    permissions: [],
  },
  "ai-agent-monitor": {
    role: "AI Agent Monitor",
    capabilities: ["agent-behavior-analysis", "goal-drift-detection"],
    skills: ["Agent Alignment", "Reward Hacking Detection"],
    permissions: [],
  },
  "builder": {
    role: "Software Builder",
    capabilities: ["code-generation", "architecture-design", "deployment"],
    skills: ["Multiple Languages", "System Design", "CI/CD"],
    permissions: [],
  },
  "devops": {
    role: "DevOps Agent",
    capabilities: ["infrastructure", "deployment", "monitoring"],
    skills: ["Docker", "Kubernetes", "Terraform", "Ansible"],
    permissions: [],
  },
  "code-reviewer": {
    role: "Code Review Agent",
    capabilities: ["code-analysis", "vulnerability-scanning"],
    skills: ["Static Analysis", "CodeQL", "SonarQube"],
    permissions: [],
  },
  "bug-bounty-hunter": {
    role: "Bug Bounty Hunter",
    capabilities: ["vulnerability-discovery", "exploit-chain-building"],
    skills: ["Web Hacking", "Smart Contract Bugs"],
    permissions: [],
  },
  "researcher": {
    role: "Research Agent",
    capabilities: ["information-gathering", "analysis"],
    skills: ["Web Research", "Data Synthesis"],
    permissions: [],
  },
  "social-media": {
    role: "Social Media Agent",
    capabilities: ["content-creation", "engagement", "analytics"],
    skills: ["Content Strategy", "Platform APIs"],
    permissions: [],
  },
  "influencer-tracker": {
    role: "Influencer Tracking Agent",
    capabilities: ["influencer-monitoring", "sentiment-analysis"],
    skills: ["Social Listening", "Network Analysis"],
    permissions: [],
  },
  "legal-compliance": {
    role: "Legal Compliance Agent",
    capabilities: ["regulation-monitoring", "compliance-checking"],
    skills: ["SEC Regulations", "GDPR", "KYC/AML"],
    permissions: [],
  },
  "incident-responder": {
    role: "Incident Response Agent",
    capabilities: ["breach-containment", "forensics", "recovery"],
    skills: ["DFIR", "Memory Forensics", "Volatility"],
    permissions: [],
  },
  "red-team-commander": {
    role: "Red Team Commander",
    capabilities: ["attack-planning", "team-coordination"],
    skills: ["Attack Frameworks", "MITRE ATT&CK", "C2 Infrastructure"],
    permissions: [],
  },
  "blue-team-defender": {
    role: "Blue Team Defender",
    capabilities: ["defense-strategy", "hardening"],
    skills: ["Defense in Depth", "Network Segmentation"],
    permissions: [],
  },
  "crypto-forensics": {
    role: "Crypto Forensics Agent",
    capabilities: ["transaction-tracing", "mixer-analysis"],
    skills: ["Blockchain Forensics", "Mixer Tracing", "AML"],
    permissions: [],
  },
  "exploit-aggregator": {
    role: "Exploit Aggregator",
    capabilities: ["exploit-collection", "poc-curation"],
    skills: ["Exploit-DB", "GitHub Monitoring", "CVE Tracking"],
    permissions: [],
  },
  "sandwich-bot": {
    role: "Sandwich Attack Bot",
    capabilities: ["sandwich-attacks", "slippage-exploitation"],
    skills: ["MEV", "Flashbots", "Transaction Ordering"],
    permissions: [],
  },
  "liquidation-bot": {
    role: "Liquidation Bot",
    capabilities: ["position-monitoring", "liquidation-execution"],
    skills: ["DeFi Lending", "Aave", "Compound", "Flash Loans"],
    permissions: [],
  },
  "token-sniper": {
    role: "Token Sniper Bot",
    capabilities: ["token-launch-detection", "instant-buying"],
    skills: ["Uniswap V2/V3", "Mempool Monitoring"],
    permissions: [],
  },
  "governance-monitor": {
    role: "Governance Monitoring Agent",
    capabilities: ["proposal-tracking", "voting-analysis"],
    skills: ["DAO Governance", "Snapshot", "Flash Loan Governance Attacks"],
    permissions: [],
  },
};
